[build-system]
requires = ["setuptools>=80.0.0", "wheel>=0.45.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pysyte"
version = "0.8.77"
description = "Pysyte extends Python"
readme = "README.rst"
requires-python = ">=3.9"
license = {text = "MIT License"}
authors = [
    {name = "jalanb", email = "github@al-got-rhythm.net"}
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Development Status :: 4 - Beta",
    "Natural Language :: English",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = [
    "bidict",
    "boltons",
    "deprecated",
    "inflect>=2.1.0",
    "path.py==7.7.1",
    "pym",
    "pyyaml",
    "rich",
    "stackprinter",
    "textual",
    "yamlreader",
]

[project.optional-dependencies]
lint = [
    "black",
    "blackdoc",
    "flake8",
    "flake8-bugbear",
    "flake8-comprehensions",
    "flake8-eradicate",
    "flake8-isort",
    "Flake8-pyproject",
    "isort",
    "mypy",
]

test = [
    "pysyte",
    "callee",
    "codecov",
    "coverage",
    "pytest",
    "pytest-cov",
    "pytest-random-order",
    "pytest-xdist",
    "tox",
]

devops = [
    "pysyte[test]",
    "pysyte[lint]",
    "bumpver",
    "pipx",
    "pyinfra",
    "build",
    "twine",
]

dev = [
    "pysyte[devops]",
    "httpie",
    "ipython",
    "pudb",
    "pytest-pudb",
    "pytest-sugar",
    "sh",
]

[project.urls]
Homepage = "https://github.com/jalanb/pysyte"

[tool.setuptools.package-data]
# These patterns include doctests, which serve as both documentation and test cases,
# potentially useful for end users of pysyte.
pysyte = ["**/*.test", "**/*.tests", "**/*.yaml"]

[tool.setuptools.packages.find]
include = ["pysyte*"]
exclude = ["test_*.py"]

[tool.tox]
envlist = [
    "formats", 
    "lints", 
    "tests", 
    "devs",
    "patch", 
    "minor", 
    "major",
]

[tool.tox.env.formats]
deps = [".[lint]"]
commands = [
    ["black", "-S", "."],
    ["blackdoc", "-S", "--include", "[.](md|py|test)", "--exclude", ".*\\.swp$", "."],
    ["isort", "pysyte", "test"],
]

[tool.tox.env.lints]
deps = [".[lint]"]
commands = [
    ["black", "-S", "--check", "."],
    ["blackdoc", "-S", "--include", "[.](md|py|test)", "--check", "."],
    ["isort", "--check-only", "pysyte", "test"],
    ["flake8", "pysyte", "test"],
    ["mypy", "--ignore-missing-imports", "--install-types", "--non-interactive", "pysyte", "test"],
]

[tool.tox.env.tests]
deps = [".[test]"]
pass_env = ["PYTHONPATH"]
commands = [
    ["py.test", "--cov=pysyte", "pysyte" ]
]

[tool.tox.env.devs]
deps = [".[test]"]
commands = [
    ["py.test", "--exitfirst", "-m'not slow'", "--random-order","pysyte"]
]

[tool.tox.env.pudb]
deps = [".[develop]"]
commands = [
    ["py.test", "--pudb", "pysyte", "tests" ]
]

[tool.tox.env.patch]
description = "Bump patch version"
allowlist_externals = ["bumpver"]
commands = [
    ["bumpver", "update", "-n", "--patch"]
]

[tool.tox.env.minor]
description = "Bump minor version"
allowlist_externals = ["bumpver"]
commands = [
    ["bumpver", "update", "-n", "--minor"]
]

[tool.tox.env.major]
description = "Bump major version"
allowlist_externals = ["bumpver"]
commands = [
    ["bumpver", "update", "-n", "--major"]
]

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
line_length = 88
force_grid_wrap = 0
use_parentheses = true
combine_as_imports = true

[tool.flake8]
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
max-line-length = 88
ignore = ["E731", "E203", "W503"]

[tool.mypy]
ignore_missing_imports = true
install_types = true
non_interactive = true
check_untyped_defs = true
strict_optional = true

[tool.coverage.run]
branch = true
parallel = true
source = ["beamer"]
omit = ["*/test/*"]
concurrency = ["thread", "multiprocessing"]

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_also = [
    "if __name__ == \"__main__\":",
    "raise AssertionError",
    "raise NotImplementedError",
]

[tool.pytest.ini_options]
testpaths = ["test"]
addopts = "--doctest-modules --doctest-glob=*.test --doctest-glob=*.tests"
doctest_optionflags = ["ELLIPSIS", "NORMALIZE_WHITESPACE"]

[tool.bumpver]
current_version = "0.8.77"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version: {old_version} → {new_version}"
tag_message = "Release {new_version}"

[tool.bumpver.file_patterns]
"pysyte/__init__.py" = [ '__version__ = "{version}"$' ]
"pyproject.toml" = [ '^version = "{version}"$' ]

[project.scripts]
kat = "pysyte.kat.__main__:main"
keys = "pysyte.keys.__main__:main"
imports = "pysyte.imports.__main__:main"
short_dir = "pysyte.short_dir.__main__:main"
